### ISSUE TITLE
Improving capture of gene ontology (GO) data in Information Editor

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1134]
Discussing the ability to capture ontology terms as well as evidence codes and supporting literature. It includes Gene Ontology as well as various anatomy and phenotype ontologies (e.g. Uberon, OMP, mouse anatomy, etc.).

Gene ID --> ontology term (e.g. GO ID) --> evidence code (e.g. ECO ID) --> PMID

Bringing @satta @cmungall @kltm to this discussion.

**Comment by nathandunn** [comment]
Should look something like this.  

![screen shot 2016-06-16 at 11 02 25 am](https://cloud.githubusercontent.com/assets/751274/16127554/d3b712e0-33b1-11e6-9e4b-9aba11e0e6f1.png)

**Comment by monicacecilia** [comment]
To start with.. and we may add other fields.

**Comment by monicacecilia** [comment]
Collection of GH issues related to this improvement:
- [ ] copy functional annotations explicitly #1118
- [ ] allow for configurable CV / CV_TERM lookups (e.g., HPO, OMP, etc.) #1119
- [ ] attach evidence codes pub IDs to cv / cv_term annotations, allow possibly more complex units #1120
- [ ] allow custom export classes for GFF3, FASTA, and Chado, and GPAD, and GAF? #1121

**Comment by selewis** [comment]
On export the annotation ("GAF") file should include the user ID as well as
the source.

-S

**Comment by nathandunn** [comment]
Okay @selewis I added it to the relevant issue.

**Comment by obsidian83** [comment]
Any update to this?

**Comment by erasche** [comment]
Unrelated to obsidian83's query, since I'd never seen this issue before, wanted to share that we had a nice UI for this, but we built it as a standalone service that was iframe'd in to apollo. https://github.com/TAMU-CPT/cacao-frontend/

**Comment by nathandunn** [comment]
@obsidian83  Unfortunately not.    Do you want to describe your use-case and I can make some recommendations or you just want to provide an actual GO annotation.

If you can use what @erasche  and @MoffMade built in the interim that would be great.   

@erasche  How does this export GO annotations with the rest of the GFF3?

**Comment by erasche** [comment]
@nathandunn it writes out a GAF file since we needed to do more than just adding GO xrefs into our gff3 would allow.

**Comment by obsidian83** [comment]
@nathandunn the use-case is to be able to use **one** piece of software to capture all an annotator/curators needs to provide good functional and structural annotation while providing the evidence for them.  
@erasche it looks like a nice piece of software, I will try it out.

**Comment by erasche** [comment]
@obsidian83 let me know if you have any questions/problems. It proably isn't super easy to set up and it probably hard codes a lot of assumptions from our old workflow which was built around supporting the gonuts program. But maybe you can make it work for you.

**Comment by nathandunn** [comment]
@erasche  / @MoffMade Does it use a separate backend?     Is there a rough install guide for how to integrate it or a high-level (this is what it is)?     Would this be appropriate to potentially integrate?  

I think the GAF output is fine, but I agree that the current GO annotations implementation (essentially a key/value) was pretty dated even 10 years ago and would love to see something like this integrated.

**Comment by cmungall** [comment]
Expressivity: GAF < GPAD < [GO-CAM](http://geneontology.org/cam)

(with a large difference between GPAD and GO-CAM)

It wouldn't make sense to reinvent a GO-CAM editor but you could federate with Noctua

For a simple bag or terms editor it would be better to target GPAD, capture full provenance of annotation

**Comment by nathandunn** [comment]
I like the idea of federating with an existing editor, but will this change the lack of richness in terms of how we represent evidence (ECO code, etc.)?

**Comment by nathandunn** [comment]
I think there was some confusion as we don't allow a ready way to provide evidence.    @obsidian83  
My advice would be:

1 - use https://github.com/TAMU-CPT/cacao-frontend/ or some version of it
2 - provide comments that indicate the GO annotation evidence that get mapped back together when reprocessing the GFF3
3 - export annotations to Chado or GFF3 and use another tool to manually provide the functional annotations.    I'm unsure if something in Galaxy (https://github.com/galaxy-genome-annotation) or if you could use Artemis (which does these annotations correctly) would be useful.  
 
To be clear, would love to implement this (and should have been done awhile ago), but we don't have the funding to do it in the way we would like.  If its something you'd be interested in developing I'd be glad to help.

**Comment by erasche** [comment]
@nathandunn

> @erasche / @MoffMade 

@elenimijalis did the vast majority of the work on CACAO, not @moffmade (Hence the edit to your comment.) That said, @moffmade is the current maintainer since he's working for the CPT.

> Does it use a separate backend?

Yep, https://github.com/tamu-cpt/cacao-backend

> Is there a rough install guide for how to integrate it or a high-level (this is what it is)? Would this be appropriate to potentially integrate?

Not really. There are containers and some instructions for various sub-components, but no overall guide since it was primarily focused on the CPT's use case.

- [frontend](https://github.com/TAMU-CPT/cacao-frontend/blob/master/Dockerfile) which has a CACAO_BACKEND_URL environment variable you must set
- [backend](https://github.com/TAMU-CPT/cacao-backend/blob/master/Dockerfile) has a decent readme + docker file, but no configurability there
- [JBrowse plugin](https://github.com/TAMU-CPT/cacao-apollo-plugin) but this just shows the result of the "review process" on the annotations.
- The backend includes [a script](https://github.com/TAMU-CPT/cacao-backend/blob/master/base/management/commands/add_org_api.py) which takes a GFF3 file and imports the data into cacao.

> @cmungall GO-CAM

We considered integration with noctua somehow but could not find a good way to do this in the context of: 1) apollo, 2) the gonuts/cacao programme we were trying to integrate with. We also considered GPAD but the existing pipelines that were being used accepted GAF only. Definitely good plans for future work.

**Comment by nathandunn** [comment]
![image](https://user-images.githubusercontent.com/751274/52087672-ede6f300-255e-11e9-983f-db5fc9cf4cd7.png)

**Comment by nathandunn** [comment]
TODO for PR:
- [ ] add UI (gene and isoform level?)
- [ ] update a GWT shared model that roughly reflects: https://github.com/TAMU-CPT/cacao-backend/blob/master/base/models.py#L62
- [ ] implement GO rules (ping @dgls2rd
- [ ] export of GFF3 for artemis style GFF3
- [ ] export as GPAD?
