### ISSUE TITLE
Testing Script ToDo list for 2.0.7 

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1669]
A) Testing functions in the main window

1. Switch between organisms:
- [x] 1. 1) Check that you can change organisms from the upper left-corner drop-down menu.

- [x] 1. 2) Check that you can switch organisms from the Organism tab in the Annotator Panel

- [x] 1. 3) Check that the organism and sequence preference is preserved only on a single browser tab. Every tab / window opened should allow a different sequence and organism. The last organism + reference sequence (e.g. scaffold, chromosome) should be loaded into each, but each browser tab will be independent.

- [x] 1. 3. 1) The last "movement" of any browser for a particular organism should become the new preference (location + scaffold) for that organism.

- [x] 1. 3. 2) The last "movement" should become the new "default" organism.

- [x] 1. 3. 3) Switching back and forth between sequences should remember the last location for each.

- [x] 1. 3. 4) Switching back and forth between organisms should remember the last location (scaffold and location) for each.

- [x] 1. 4) Switch between organisms after creating annotations on this reference sequence (e.g. scaffold, chromosome), if the two reference sequences have the same name in two (or more) different organisms.

- [x] 1. 4. 1) Use the JBrowse drop-down or search menu to navigate between the two scaffolds on different organisms at least twice and confirm that annotations that belong to an organism on one scaffold are only seen on that organism and not the other.

- [x] 1. 4. 2) Use the Sequence Panel to confirm that scaffolds on a particular organism only belong to that organism. i.e., every scaffold listed should be part of the current organism.

- [x] 1. 4. 3) Use the Sequence Dropdown to confirm that scaffolds on a particular organism only belong to that organism.

- [x] 1. 4. 4) Use the Annotator Panel "Go To Annotation" button to confirm that scaffolds listed for a particular organism and scaffold only belong to that organism.

2. Test top-level menu options:
2.1)  Login / Logout:

- [x] Test that you are able to logout using the options on the upper right corner of the main window by clicking on your user ID and choosing to 'logout'. Then, test that you are able to log back in.

- [x] Test that all browsers log out for a set user.

- [x] When logged out you should still be able to view "public" organisms and browse public genomes from the link on the login screen.

2.2) File

- [x] /Open (Test that data can be loaded locally using URLs (File / Open / Remote URLs)).

- [x] /Add Combination Track: test that the arithmetic combination of quantitative tracks is possible by dragging two of them into a 'combination track'. Test different operations (addition, substraction) and arrangements (left and right positions for each track) as appropriate.

- [x] /Add Sequence Search Track and perform a search test.

- [x] 2. 3) View

Check the ability to set and clear highlights, show plus/minus strands, show track label, resize quantitative tracks, color by CDS, and changing the color scheme (dark or light).

- [x] 2. 4) Tools: From Tools menu, query the genome with BLAT, using an amino acid or nucleotide sequence. For example: Housekeeping gene Calpain small subunit 1 CPNS1, CAPNS1, CAPN4, CAPNS (UniProt).

sp|P04632|CPNS1_HUMAN Calpain small subunit 1 MFLVNSFLKGGGGGGGGGGGLGGGLGNVLGGLISGAGGGGGGGGGGGGGGGGGGGGTAMRILGGVISAISEAAAQYNPEPPPPRTHYSNIEANESEEVRQFRRLFAQLAGDDMEVSATELMNILNKVVTRHPDLKTDGFGIDTCRSMVAVMDSDTTGKLGFEEFKYLWNNIKRWQAIYKQFDTDRSGTICSSELPGAFEAAGFHLNEHLYNMIIRRYSDESGNMDFDNFISCLVRLDAMFRAFKSLDKDGTGQIQVNIQEWLQLTMYS
Clear the highlighted region using the option from the View menu.

- [x] 2. 5) Help: Check that all links go to a new screen.

3. Test the Navigation Bar

- [x] 3. 1) Search for an indexed gene (e.g. in honey bee demo CSN2_DANRE (it's on Group1. 37:152689..155265) by typing the gene name on the search box in the middle of the navigation bar in the main window.

- [x] 4. Drag and drop a gene onto the “User-created Annotations” (U-cA) area.

- [x] 5. Zoom in (double click) to inspect last exon (5'-3') of the displayed gene and:

- [x] 5. 1) Change intron/exon boundary (dragging)

- [x] 5. 2) Check the recalculated ORF

- [x] 5. 3) Color by CDS using the corresponding option from the View top-level menu

6. 'Zoom to Base Level' to reveal DNA Track and test sequence annotation alterations:

- [x] 6. 1) Insertions

- [x] 6. 2) Deletions

- [x] 6. 3) Substitutions

7. 'Zoom back out', then reveal right-click menu.

7.1) Test:

- [x] 7.  1) Get Sequence, Get GFF3

- [x] 7. 1. 2) Delete, Merge, Split, Duplicate, Make Intron, Move to Opposite Strand.

- [x] 7. 1. 3) Set Translation Start, Set Translation End, Set Longest ORF, Set Readthrough Stop Codon.

- [x] 7. 1. 4) Set to Downstream Splice Donor, Set to Upstream Splice Donor, Set to Downstream Splice Acceptor, Set to Upstream Splice Acceptor.

- [x] 7. 1. 5) Check the Undo and Redo operations

- [x] 7. 1. 6) Show History from the right click menu, and test the ability to revert to any of the previous versions of the feature by clicking on the arrow buttons to the right of each version.

- [x] 7. 1. 7) Annotation Information Editor: Name, Symbol, DBXRefs, Comments, Gene Ontology IDs, and PubMed IDs.

- [x] 7. 1. 8) Use both the genomic feature you are currently annotating and a genomic feature from one of the evidence tracks to modify the exon and UTR boundaries for the annotation in the User-created Annotations area using the following operations from the right-click menu: Set as 3' end, Set as 5' end, Set both ends.

- [x] 7. 1. 9) Set exon boundary to create and remove an isoform, and use History to conduct Undo / Redo operations on this isoform.

- [x] 7. 1. 10) Change the annotation type from the right-click menu and check Undo / Redo operations on this annotation.

8. URLs and Real time.

- [x] 8.1) Check that the URL can be used for sharing work (on a different browser) for both logged in and logged out (JBrowse only) mode: bring up different browser window and paste the shared URL. 

- [x] 8.2) Check real-time update by dragging and dropping another exon to the model on the left (same strand); check that “non-canonical boundaries” warning sign appears as appropriate. Last, delete an exon, Redo/Undo to test.

9. Export

- [x] 9.1) Check that you are able to export data from the User-created Annotations track using the drop down menu option (from the track label) and choosing the 'Save track data' option. 

- [x] 9.2) Check both GFF3 (with and without FASTA) and FASTA files (CDS, cDNA, peptide, and highlighted region (note: remember to first highlight a region to test this)).

B) Testing the Annotator Panel

- [x] 10. Check that you can switch between organisms using both the drop-down menu in the upper left corner of the Annotator Panel and the options in the and the Organism tab.

- [x] 11. Test that you are able to logout by clicking on the 'logout' arrow located in the upper right corner of the Annotator Panel. Then, test that you are able to log back in.

- [x] 12. Test changing the user's password using the options available when clicking on the user ID button in the upper right corner of the Annotator Panel.

13. Test functionality for each of the tabs in the panel.

13.1) Annotations

- [x] 13. 1. 1) Check that you can navigate to an annotation by clicking on them from the list in the panel. Annotations for gene elements that produce transcripts will require one click on the name of the annotation, then double clicking on the transcript.

- [x] 13. 1. 2) Navigate To Annotation Details

- [x] 13. 1. 2. 1) After clicking on an annotation, click on the Details tab at the bottom of the Annotator Panel to display metadata for each annotation. Then, click on the Coding tab to reveal a list of exons, and click on one of the exons to reveal options to modify its boundary using the arrows in the display. Modify a number explicitly and click outside the box. Confirm that a change was made for a legitimate value.

- [x] 13. 1. 2. 2) Repeat for pseudogenes and non-coding RNAs.

- ~~13. 1. 2. 3) Repeat for Repeat Region and Transposable Element.~~

- [x] 13. 1. 3) Find an annotation using the Annotation Name search box, and use the filters from the drop down menus.

13.2) Tracks

- [x] 13. 2. 1) Check the display of evidence available on all tracks by clicking to "check" and "uncheck" from the list of available tracks.

- [x] 13. 2. 2) Search for a track using the search box.

- [x] 13. 2. 3) Check that clicking on the show JBrowse tracks selector icons properly toggles the native tracks.

- [x] 13. 2. 3. 1) Click on the track panel and confirm that doing and undoing the toggle switch toggles the JBrowse tracks view and the main panel toggle icon.

- [x] 13. 2. 3. 2) Click on the main panel toggle button and confirm that doing and undoing the toggle switch toggles the JBrowse tracks view and switches the track panel toggle as well.

- [x] 13. 2. 3. 3) Confirm that reload in either case saves the prior preference.

- [x] 13. 2. 3. 4) Test as Admin and non-Admin for one case to confirm layout.

13.3) Ref Sequence

- [x] 13. 3. 1) Use the search box to find a scaffold / chromosome and navigate to it by double clicking on one of them.

- [x] 13. 3. 2) Test that you can export GFF3 and FASTA files for one or more selected scaffolds at a time.

13.4) Organism

- [x] 13. 4. 1) Check that you can alter the metadata or source file for existing organisms, add new organisms, and delete current organisms.

- [x] 13. 4. 2) Test that you can switch between organisms by double clicking on one of them.

13.5) Users

- [x] 13. 5. 1) Create a new user and grant read, write, and publish permissions.

- [x] 13. 5. 2) Test altering information and permissions and group membership for users.

13.6) Groups

- [x] 13. 6. 1) Test that you can add and delete groups, as well as assign users to these groups.

13.7) Admin

- [x] 13.7.1) Click and corroborate that each item listed under the Admin tab sends you to a new page. And test that you can add and delete fields and data as needed for each page.

13.8) Public link

- [x] 13. 8. 1) Confirm that clicking on a public link option in the main window when logged in will forward you to the Annotator Panel view.

- [x] 13. 8. 2) Confirm that clicking on a public link option in the main window when logged out will give you the regular "JBrowse view".

Check that this link opens up a new window showing only the browser and JBrowse track menu, without the annotator panel. When logging in, it should redirect to another login menu and then finally end up at the Annotator Panel view with the same tracks selected.

13.9) Logged in link

- [x] 13. 9. 1) Confirm that clicking on a logged in link option in the main window when logged in will forward you to the Annotator Panel view directly.

- [x] 13. 9. 2) Confirm that clicking on a logged in link option in the main window when logged out will take you to the login screen and then redirect you to the proper Annotator Panel view when approved with the same selections in-tact.

C) Testing Integration

14. Test security redirect

- [x] 14. 1) Test redirect by clicking on a JBrowse (public URL) link and then clicking login.

- ~~14. 2) Test through a proxy (nginx, apache, etc.)~~

- [x] 14. 3) Test copy and pasting a logged in URL (goes to loadLink)

- [x] 14. 4) When logged out and logging back in should come back to the same place.

- [x] 14. 4. 1) Should work even if on different browser.

D) Testing Web Services: @nathandunn / @deepakunni3 to report on this portion. 
Also, please test this item: 14. 2) Test through a proxy (nginx, apache, etc.)

**Comment by monicacecilia** [comment]
I completed testing on 2.0.7 and reported all issues [here](https://github.com/GMOD/Apollo/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.7+author%3Amonicacecilia).

**Comment by monicacecilia** [comment]
@deepakunni3 @nathandunn 
I am assuming you both saw this note at the bottom of this issue. Just adding an extra-nudge to remind you both. Thank you!

> D) Testing Web Services: @nathandunn / @deepakunni3 to report on this portion.
Also, please test this item: 14. 2) Test through a proxy (nginx, apache, etc.)
