### ISSUE TITLE
refork 2.1.0 from master and backport

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1829]
Closes #1612.

After we get all of the tracks converted (#1827, #1825, #1778, etc.).  

We need to rebranch from master and add:
- [ ] URL scheme to use "reverse=true": #1829
- [ ] pull in other tracks from the older 2.1.0 branch: #1831
- [ ] re-add UI components to GWT top and the JBrowse the top-menu #1832
- [ ] finish conversion of projection library and move hooks: https://github.com/nathandunn/linear-projection: #1833
