### ISSUE TITLE
BRC4 metadata from OGS tracks should be viable

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2364]
from #2282 and #2235 

- [x] export with DBXref, description (done), key / value, comment , status, symbol, synonyms
- [x] confirm when importing track that they all show up and they get copied over with import / export
- [x] implement gene products #2312 
- [x] implement generic evidence #2234 
- [x] confirm that we can do a GO load #2173 
- [x] make sure we can properly import all properties from a GFF3 for gene products and generic evidence

**Comment by nathandunn** [comment]
What is in there from #2282 won't be sufficient, but I think it will be sufficient to start figuring out how and where to add exports as we get more and more GFF3s.

**Comment by nathandunn** [comment]
I think all of this work, but needs to be tested.
