### ISSUE TITLE
Create Projection v2

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#895]
## TODO:
- [x]  pull off of github master for JBrowse (local fork . . v2) . . locally fork back  -1
- [x]  remove reference track stuff - 1
- [x] improve the “region” code to decorate for locations in the contiguous regions themselves if there are more than one or we are projecting a simple feature - 4 
- [x]  add back features (including contiguous features) - 4
  - [x] show features in draggable box
  - [x] show features in grid
  - [x] persist combination 
  - [x] visualize single scaffold (again)
  - [x] visualize combined scaffold (again)
  - [ ] visualize single feature in browser (a projection):
    - [x] pass sequenceList fmin/fmax into updateGenomeLocation (somehow missing)
    - [x] every sequence should have a start and end (non-0 if feature)
    - [x] project features properly,  0-N instead of S-S+N
      - [x] fmin is not being remapped properly in FeatureProjectionService
    - [ ] **set properly view limits (0-N) for bookmark** - instead of original sequence
  - [x] **visualize combined features** ( ```trackData.json``` -> projectTrackData has a bad offset)
- [ ] **make bookmarks default instead of sequences (so comes back to the same place)**
- [ ] fix "chunk" data sequences (including adjacent and including "features")
- [ ]  add “folding” concept to interface for individuals (which need to be decorated as below) . .  use a vertical line, but jagged edges (or waves) all the way down - 4:
   - [ ] 2 exons 
   - [ ] entire transcript
   - [ ] use the “region” code to decorate the folding (should be fully vertical and indicate regions folded) . . this will help indicate it in the tracks - 8
- [ ] annotate features:
   - [ ] annotate on either first or second scaffold
   - [ ] update should show up in correct place
   - [ ] annotate across scaffold  
- [ ] pull off the labels correctly . . getting rid of the “scaffold” . . this can be part of a plugin . . or just part of Apollo . . . might be easier - 4 
- [ ] in GenomeView, add LocationScaleTrack to decorate the view
- [ ] use [spring content caching](http://gpc.github.io/grails-springcache/docs/guide/4.%20Content%20Caching.html) to do speedups 

```
      {
            "start": 17,
            "end": 932,
            "id": 3,
            "id": 3,
            "sequenceList":[
                {
                    "name":"chr1", 
                    "start": 123, 
                    "end": 789
                    "reverse": false
                    "feature": {"name":"SOX9"},
                    "folding":[
                        {"fmin":300,"fmax":532}
                    ]
                }
            ]
        }
```

## Use-cases

- [ ] (A) **scrunch 1 intron between exons**
  - [ ] **change "fold" link to "Annotation Genometry" . . shows exons + details**
  - [ ] create projections off of "fold" in sequence
  - [x] link in UI to add **fold** menu between two exons
  - [x] add a global store for current state (which every track must pick out) -> DiscontinuousProjection:List<Coordinate>, Coordinate:min,max,sequence/org
  - [x] only port discontinuous projection
  - [ ] project each track (little inner-notch)
  - [ ] update track scale rendering (inner and outer)
  - [ ] project at least bigwig track
- [ ] (B) **scrunch all introns in one gene**
  - [ ] same as above
- [x] (C) **view contiguous scaffolds (same as above use MultisequenceProjection)**:
  - [ ] update the trackScale to reflect changes
  - [ ] do annotation properly
- [ ] (D) **view contiguous scaffolds of single genes**
  - [ ] same as above, but have very specific coordinates

**Datastructure**: Putative datastructure used for display.  Note that the "folding" is different as it indicates the areas we are hiding (and need to indicate).  Features indicate the areas that we are showing.   In the sequenceList we need to be able to the region.  The "features" portion is for decoration as is the "folding" region.

**Comment by nathandunn** [comment]
Create fold method:

Rightedge - left edge  .. Projection .. Note (json) 

Project feature: 

Fmin fmax .. Projection .. Note (json)

Multiple projections e.g. Reverse complement .. Store a list of projections to apply 

Display .. Sketch note 

![from skitch](https://cloud.githubusercontent.com/assets/751274/13294368/88618014-dad8-11e5-9b4f-a3b9539c6a14.png)

Projection notation should be (red is flipped, blue is not or vice versa):  

![image](https://cloud.githubusercontent.com/assets/751274/13294537/488372a8-dad9-11e5-9db6-645472dd14b0.png)

With Genes:

![image](https://cloud.githubusercontent.com/assets/751274/13294528/36764b3a-dad9-11e5-89cf-4ab9009a2f02.png)

A Gene crossing scaffold:


![image](https://cloud.githubusercontent.com/assets/751274/13294586/823248c6-dad9-11e5-88fb-3274e2b81c2f.png)

**Comment by nathandunn** [comment]
Note: 1-base vs interbase:  http://transvar.org/6111/interbase.pdf

We are using 1-base (same as GFF3), though internally, I think that JBrowse is using interbase (bed files, etc.).

**Comment by nathandunn** [comment]
will try adding an extra track for the display . .  should be REST based initially

**Comment by nathandunn** [comment]
so there are a few different approaches that we've looked at.  Our biggest hinderances are: 1) we don't want to rewrite JBrowse and 2) we need appropriate visualizations 3) we don't have an appropriate model store / alternate view for our data.  

I'm curious why . . . instead of modifying store functions, if we used REST directly, but this is sort of what we were already doing with the server-side mangling.    

To create the REST-side alternate "view" track, I think we could just display a "feature" labelled "Projection Legend (785-913)".  This will allow counting.  You could even count by 10's or something, internally, displaying as exons, etc.  From [here](http://gmod.org/wiki/JBrowse_Configuration_Guide#JBrowse_REST_Feature_Store_API) you could

**Comment by nathandunn** [comment]
Components to Consider
=====
- [ ] bookmark creation from sequences, annotations, etc.
- [ ] allow for named bookmark
- [ ] get rid of "label" in JBrowse screen other than for "lookup" or bookmark label . . highlight is in annotator panel only (maybe above? . . all the way above?)
- [ ] view popups in JBrowse screen for evidence 
- [x] view popups in Apollo annotation track 
- [ ] create annotation from evidence
- [ ] modify coordinates with evidence (e.g,. modifying exon boundary)
- [ ] add Util for going between 1-base versus interbsae
- [ ] handle the different track types
- [ ] we need to visualize where we're / coordinate-wise
- [ ] we need to visualize what we are looking at overall

Implications of doing on the client versus the backend
=====
- Anything on the GWT-side does not really change much. 
- All popups are going to have to be over-written, using a pre-supplied function or not. 
- We have to port our code over to the client to simplify some of this.
- Visualization can kind of be faked, in a similar manner.

**Comment by nathandunn** [comment]
closing in favor of #895
